name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -d '{
                 "username": "GitHub Bot",
                 "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                 "content": "🚀 A new pull request has been opened!\n**Title:** Update README.md\n**URL:** https://github.com/Luan-Web3/bitcoin-wallet-desktop/pull/3\n**Author:** Luan-Web3"
               }' \
               $DISCORD_WEBHOOK_URL
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}